apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: ${K8S_NAMESPACE}
type: Opaque
stringData:
  FLASK_SECRET_KEY: "${FLASK_SECRET_KEY}"
  MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
  KAFKA_PASSWORD: "${KAFKA_PASSWORD}"