apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: ${K8S_NAMESPACE}
type: Opaque
data:
  FLASK_SECRET_KEY: "MTJhYmNkZWYxMjM0NTY3ODkwYWJjZGVmMTIzNDU2Nzg="  # 생성된 실제 base64 값
  MYSQL_PASSWORD: "SGM4WERqNFBkag=="  # testpassword를 base64로 인코딩
  REDIS_PASSWORD: "R2pBMFBIeDk2Tg=="  # GjA0PHx96N를 base64로 인코딩
  KAFKA_PASSWORD: "" 