apiVersion: v1
kind: Secret
metadata:
  name: eventhub-secret
  namespace: ${K8S_NAMESPACE}
type: Opaque
data:
  # Event Hubs 연결 문자열 (base64로 인코딩된 값)
  # echo -n "your-connection-string" | base64
  connection-string: <base64-encoded-connection-string>
  
  # Event Hubs 이름
  eventhub-name: <base64-encoded-eventhub-name>
  
  # Consumer Group
  consumer-group: <base64-encoded-consumer-group>
